print ("why did andrew go to the cafateria")
input ()
print ("because he was hungary")
input ()
print ("why did the chicken cross the road")
input ()
print ("because he wanted to get to the other side")
input ()
name = input("what is your name? ")
input ()
print (f"hello {name} and welcome to ct8")