name = input("hey what is your name?")
print(f"hello {name} hope your doing well")
input()
print("today I will be telling you a story with your help")
print("pick a animal")
animal = input()
print("pick a location") 
location = input() 
print("pick a color")
color = input ()
print("pick a verb")
verb = input ()    
print("")
print("pick a sport")
sport = input ()
print("pick a item")
item = input ()
print("One day, a", color, animal, "went to", location + ".")
print("The", animal, "loved to", verb, "everywhere it went.")
print("While walking around", location + ", the", animal, "found a", item + ".")
print("Soon, some kids invited the", animal, "to play", sport + ".")
print("The", color, animal, "was great at", sport, "and everyone cheered.")
print("At the end of the day, the", animal, "took the", item, "home and said it was the best day ever.")